### ISSUE TITLE
Slots issue

### ISSUE THREAD

**Issue by tozzleboy** [tovyblox/tovy#14]
If you claim a slot before a session has an owner, you get a lovely error and an un-usable sessions page.
![image](https://user-images.githubusercontent.com/55185704/208285951-4c18f6d6-27d5-4b78-a80d-a0ed7036df62.png)

**Comment by marinofranz** [comment]
Thanks, I'll check it out shortly. :)

**Comment by marinofranz** [comment]
@tozzleboy Is this issue still happening to you? We pushed out a fix.

**Comment by marinofranz** [comment]
Stale issue, closing. Comment again to have it re-opened
