### ISSUE TITLE
Next Not Found

### ISSUE THREAD

**Issue by phyouthcenter1** [tovyblox/tovy#26]
![image](https://github.com/tovyblox/tovy/assets/67077196/e2c45e92-263b-4890-a2bf-b67b1652254b)

Trying to build for production

**Comment by phyouthcenter1** [comment]
I tried running ```npm i -g next``` and I got the following error when running ```npm run build```

![image](https://github.com/tovyblox/tovy/assets/67077196/1556a264-5eff-46c8-8101-ef224c51664b)

**Comment by marinofranz** [comment]
Hi, sorry for the late response

Did you install all project dependencies before building the project?

**Comment by phyouthcenter1** [comment]
Yes, I did.

**Comment by marinofranz** [comment]
What is the installed Node.js version?

**Comment by phyouthcenter1** [comment]
![image](https://github.com/tovyblox/tovy/assets/67077196/6f56284f-7799-487b-8c0d-8bd04ea00f5d)

**Comment by phyouthcenter1** [comment]
![image](https://github.com/tovyblox/tovy/assets/67077196/7483229f-a406-4c2a-892d-45a3df6b9b24)

**Comment by phyouthcenter1** [comment]
Do you have any ideas to fix the error?

**Comment by marinofranz** [comment]
]f you're still looking for a solution, I'd recommend installing at least version [`20.10`](https://nodejs.org/dist/v20.10.0/node-v20.10.0-x64.msi) of Node.js.
