### ISSUE TITLE
Origin DNS Error on cloud.tovyblox.xyz + 500 Error on app.tovyblox.xyz

### ISSUE THREAD

**Issue by natewombwell** [tovyblox/tovy#28]
its a simple cloudflare 1016 error
Here is the image:
![error image (refresh to view or your browser isnt working???)](https://github.com/tovyblox/tovy/assets/89249903/690b8157-4701-4f28-ae7e-b511e113e4b2)
What is happening?

**Comment by natewombwell** [comment]
Here is another error:
500 HTTPS error on app.tovyblox.xyz
Image:
![this image didnt load](https://github.com/tovyblox/tovy/assets/89249903/992ff19d-4192-45e0-8c01-4458d3e0b01b)

**Comment by Zachary2311** [comment]
Tovy shutdown.

**Comment by thatonefennec** [comment]
@natewombwell Tovy is no longer under active development. We discontinued support for Tovy in order to pursue development of [Relatio](https://relatio.cc) if you would like to check it out.
