### ISSUE TITLE
HTTP > HTTPS Fix (Websocket Errors)

### ISSUE THREAD

**Issue by thatrelevantperson** [tovyblox/tovy#49]
I've noticed that Tovy is only built to be based around **http** urls instead of **https**.
I'm using NGINX & Cloudflare to connect the website to a domain and include HTTPS Encryption.

Using this guide: [Hyperlink URL](https://qdmana.com/2021/08/20210831144329645l.html)
Specifically this line of code:
const url = `${protocol === 'https' ? 'wss' : 'ws'}://${host}/socket/websocket/mineStatus/${this.$store.getters.userId}\\

This should detect whether the app is on HTTP or HTTPs (theoretically).
I need someone to help me prove this theory. I can make a guide for NGINX to proxy for Tovy.

**Comment by thatrelevantperson** [comment]
Go to the guide to see the line of code as GitHub doesn't really like it that much.

**Comment by ItsWHOOOP** [comment]
rolled out
